export const BLOG_ANALYSIS_HISTORY_KEY = "BLOG_ANALYSIS_HISTORY_KEY";
export const BLOG_RANK_HISTORY_KEY = "BLOG_RANK_HISTORY_KEY";
export const SEARCH_KEYWORD_HISTORY_KEY = "SEARCH_KEYWORD_HISTORY_KEY";
export const POST_DETAIL_HISTORY_KEY = "POST_DETAIL_HISTORY_KEY";
